# backend/tesseract_setup.py
import os
import sys
import subprocess
import platform

def check_tesseract_installed():
    """Check if Tesseract is installed and accessible"""
    system = platform.system()
    
    if system == "Windows":
        common_paths = [
            r"C:\Program Files\Tesseract-OCR\tesseract.exe",
            r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe",
        ]
        for path in common_paths:
            if os.path.exists(path):
                return path
        # Try using 'where' command
        try:
            result = subprocess.run(['where', 'tesseract'], capture_output=True, text=True)
            if result.returncode == 0:
                return result.stdout.strip().split('\n')[0]
        except Exception:
            pass
    else:
        # Linux/Mac
        try:
            result = subprocess.run(['which', 'tesseract'], capture_output=True, text=True)
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
    
    return None

def install_tesseract_windows():
    """Instructions for installing Tesseract on Windows"""
    print("=" * 60)
    print("TESSERACT NOT FOUND!")
    print("=" * 60)
    print("\nPlease install Tesseract OCR:")
    print("1. Download from: https://github.com/UB-Mannheim/tesseract/wiki")
    print("2. Run the installer (e.g., tesseract-ocr-w64-setup-5.3.3.20231005.exe)")
    print("3. During installation, check language data you need (Hindi, etc.)")
    print("4. Default install path: C:\\Program Files\\Tesseract-OCR\\")
    print("\nAfter installation, restart your terminal and run this script again.")
    print("=" * 60)

def main():
    tesseract_path = check_tesseract_installed()
    
    if tesseract_path:
        print("✅ Tesseract found at:", tesseract_path)
        print("\nTesting Tesseract version...")
        try:
            result = subprocess.run([tesseract_path, '--version'], capture_output=True, text=True)
            print(result.stdout)
        except Exception:
            print("Could not get version")
        
        # Create a config file for the backend
        config_content = f"""
# Tesseract OCR Configuration
# Generated by tesseract_setup.py

TESSERACT_PATH = r"{tesseract_path}"
TESSERACT_DATA_DIR = r"{os.path.dirname(tesseract_path)}/tessdata"
"""
        with open("tesseract_config.py", "w") as f:
            f.write(config_content)
        print("\n✅ Configuration saved to: tesseract_config.py")
        
    else:
        install_tesseract_windows()
        return False
    
    return True

if __name__ == "__main__":
    main()